# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/zybo_constr.xdc

# Block Designs: bd/color_design/color_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_design || ORIG_REF_NAME==color_design} -quiet] -quiet

# IP: bd/color_design/ip/color_design_processing_system7_0_0/color_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_design_processing_system7_0_0 || ORIG_REF_NAME==color_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/color_design/ip/color_design_PmodCOLOR_0_0/color_design_PmodCOLOR_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_design_PmodCOLOR_0_0 || ORIG_REF_NAME==color_design_PmodCOLOR_0_0} -quiet] -quiet

# IP: bd/color_design/ip/color_design_xbar_0/color_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_design_xbar_0 || ORIG_REF_NAME==color_design_xbar_0} -quiet] -quiet

# IP: bd/color_design/ip/color_design_auto_pc_0/color_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_design_auto_pc_0 || ORIG_REF_NAME==color_design_auto_pc_0} -quiet] -quiet

# IP: bd/color_design/ip/color_design_ps7_0_axi_periph_0/color_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==color_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/color_design/ip/color_design_rst_ps7_0_50M_0/color_design_rst_ps7_0_50M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==color_design_rst_ps7_0_50M_0 || ORIG_REF_NAME==color_design_rst_ps7_0_50M_0} -quiet] -quiet

# XDC: /home/kevin/Documents/ECE520/projectFinal/project-final/Hardware/Pmod_color_reading/Pmod_color_reading.gen/sources_1/bd/color_design/color_design_ooc.xdc
